### ISSUE TITLE
How should we store images?

### ISSUE THREAD

**Issue by cupakromer** [ScrappyAcademy/store_engine#1]
What gem to use to store images should we use? Top two seem to be:
- [Paperclip](https://github.com/thoughtbot/paperclip/)
- [Carrierwave](https://github.com/jnicklas/carrierwave)

Does anyone have experience with both? Thoughts? Comments?

**Comment by paulmederos** [comment]
I've use CarrierWave and Fog to upload to AWS. Followed the RailsCast with good success :)

Keep in mind this was with Heroku hosting, so the Amazon storage as necessary since Heroku clears uploaded items unless they are part of the codebase slug.

**Comment by cupakromer** [comment]
That's a good point on Heroku. I hadn't thought about how to retain the images long term.

**Comment by seanmarcia** [comment]
I vote paperclip... Easy to use and integrates with S3 super easily.

On Thu, Jul 12, 2012 at 12:45 PM, Aaron Kromer <
reply@reply.github.com

**Comment by arn-e** [comment]
No experience with either.  I would probably simply flip a coin.  There
definitely does not seem to be a definitive answer.  One small discussion :

http://stackoverflow.com/questions/7419731/rails-3-paperclip-vs-carrierwave-vs-dragonfly-vs-attachment-fu

**Comment by daidekman** [comment]
I have used both and my latest project ended up with Carrierwave, Fog, and AWS (as I notice Paul mentioned above too). I had previously used Paperclip and it did integrate with S3. I don't remember precisely the downsides, but it may have had to do with integrating with tools to manipulate the images to re-size and fit into the views. I would have to dig back, though, to confirm that.

**Comment by cupakromer** [comment]
After watching the railscast :+1: for carrierwave

**Comment by jwieringa** [comment]
I have used paperclip, would be interesting to see carrierwave. :)

**Comment by cupakromer** [comment]
So carrierwave won tonight.
