### ISSUE TITLE
View layouts and responsive design

### ISSUE THREAD

**Issue by cupakromer** [ScrappyAcademy/store_engine#3]
This might be getting ahead a bit, but thoughts on [Twitter Bootstrap](http://twitter.github.com/bootstrap/) vs. [Formtastic](https://github.com/justinfrench/formtastic) vs. hand rolling your own?

**Comment by cupakromer** [comment]
My 2cents, looked at Formtastic the other day. I wasn't a big fan of how it was handling things. I've never used Twitter Bootstrap (yet) but it looks cool. Hand rolling is fun, but can take a lot of time.

**Comment by seanmarcia** [comment]
Bootstrap/kickstrap with simpleform :)

On Thu, Jul 12, 2012 at 12:53 PM, Aaron Kromer <
reply@reply.github.com

**Comment by arn-e** [comment]
I would vote for either Bootstrap or hand rolled.  The former is just plain
ubiquitous whereas the latter might be an interesting learning experience.

**Comment by daidekman** [comment]
Bootstrap is outstanding and super-easy. One huge benefit is the tons of support in the community when questions arise (due to such widespread use). Another benefit is that it has become a bit of a platform on which designers are adding their code. One recent example is here (there are others): http://ajkochanowicz.github.com/Kickstrap/index.html

**Comment by seanmarcia** [comment]
I agree, that's why I said bootstrap/_kickstrap_ :) Great minds...

On Thu, Jul 12, 2012 at 11:35 PM, Dave Aidekman <
reply@reply.github.com

**Comment by cupakromer** [comment]
Checked out the Railscast on Simple Form. Not sure how I feel about it, but willing to give it a try.

So vote time.

:+1: bootstrap/kickstrap/simple form

**Comment by daidekman** [comment]
+1 bootstrap

I don't quite see the need for Simple Form, but it's fine. Neutral on that one.
@SeanMarcia Just noticed your _kickstrap_ mention as well - you're steps ahead of me.

**Comment by cupakromer** [comment]
Ok, looks like we have +3 on this one. :shipit: Closing
